name: CI/CD Pipeline

on:
  push:
    branches: 
      - main
      - ci-cd
  pull_request:
    branches: 
      - main
      - ci-cd

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        source: "dist/"
        target: "C:\\Users\\18287\\deployments\\"  # Ajusta esto al directorio deseado en tu servidor
